=== ornlneutronimaging/iMars3D/src/imars3d/backend/workflow/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Schema for coordinating processing in imars3d",
  "type": "object",
  "properties": {
    "facility": {
      "type": "string",
      "enum": ["HFIR", "SNS"],
      "description": "Facility for the measurment"
    },
    "instrument": {
      "type": "string",
      "enum": ["CG1D", "SNAP"],
      "description": "Instrument for the measurment"
    },
    "ipts": {
      "type": "string",
      "description": "The full IPTS identifier for the measurement"
    },
    "name": {
      "type": "string",
      "description": "Rememberable name for the measurement"
    },
    "workingdir": {
      "type": "string",
      "description": "Directory to write intermediate results when requested"
    },
    "outputdir": {
      "type": "string",
      "description": "Directory to write final results"
    },
    "tasks": {
      "type": "array",
      "minItems": 1,
      "description": "Each task is a step in the tomographic reconstruction",
      "items": {
        "properties": {
          "name": {
            "type": "string",
            "description": "Friendly name for the task"
          },
          "function": {
            "type": "string",
            "description": "Fully qualified python name for the task"
          },
          "inputs": {
            "type": "object",
            "description": "Dictionary of inputs to the task. These are in the form of key value pairs that are passed into the task."
          },
          "outputs": {
            "type": "array",
            "description": "List of outputs from the task"
          }
        },
        "required": ["name", "function"]
      }
    }
  },
    "required": ["facility", "instrument", "ipts", "name", "workingdir", "outputdir", "tasks"]
}

=== ornlneutronimaging/iMars3D/tests/data/json/good_non_interactive_full.json
{
    "facility": "HFIR",
    "instrument": "CG1D",
    "ipts": "IPTS-1234",
    "name": "name for reconstructed ct scans",
    "workingdir": "/path/to/working/dir",
    "outputdir": "/tmp/imars3d/",
    "tasks": [{
            "name": "task1",
            "function": "imars3d.backend.io.data.load_data",
            "inputs": {
                "ct_dir": "/HFIR/CG1D/IPTS-25777/raw/ct_scans/iron_man",
                "ob_dir": "/HFIR/CG1D/IPTS-25777/raw/ob/Oct29_2019/",
                "dc_dir": "/HFIR/CG1D/IPTS-25777/raw/df/Oct29_2019/",
                "ct_fnmatch": "*.tiff",
                "ob_fnmatch": "*.tiff",
                "dc_fnmatch": "*.tiff"
            },
            "outputs": ["ct", "ob", "dc", "rot_angles"]
        },
        {
            "name": "task2.1",
            "function": "imars3d.backend.morph.crop.crop",
            "inputs": {
                "arrays": "ct",
                "crop_limit": [552, 1494, 771, 1296]
            },
            "outputs": ["ct"]
        },
        {
            "name": "task2.2",
            "function": "imars3d.backend.morph.crop.crop",
            "inputs": {
                "arrays": "ob",
                "crop_limit": [552, 1494, 771, 1296]
            },
            "outputs": ["ob"]
        },
        {
            "name": "task2.3",
            "function": "imars3d.backend.morph.crop.crop",
            "inputs": {
                "arrays": "dc",
                "crop_limit": [552, 1494, 771, 1296]
            },
            "outputs": ["dc"]
        },
        {
            "name": "task3",
            "function": "imars3d.backend.corrections.gamma_filter.gamma_filter",
            "inputs": {
                "arrays" : "ct"
            },
            "outputs": ["ct"]
        },
        {
            "name": "task4",
            "function": "imars3d.backend.preparation.normalization.normalization",
            "inputs": {
                "arrays": "ct",
                "flats": "ob",
                "darks": "dc"
            },
            "outputs": ["ct"]
        },
        {
            "name": "task5",
            "function": "imars3d.backend.corrections.denoise.denoise",
            "inputs": {
                "arrays": "ct"
            },
            "outputs": ["ct"]
        },
        {
            "name": "task6",
            "function": "imars3d.backend.corrections.ring_removal.remove_ring_artifact",
            "inputs": {
                "arrays": "ct"
            },
            "outputs": ["ct"]
        },
        {
            "name": "task7",
            "function": "imars3d.backend.diagnostics.rotation.find_rotation_center",
            "inputs": {
                "arrays": "ct",
                "angles": "rot_angles",
                "in_degrees": true,
                "atol_deg": 0.5
            },
            "outputs": ["rot_center"]
        },
        {
            "name": "task8",
            "function": "imars3d.backend.reconstruction.recon",
            "inputs": {
                "arrays": "ct",
                "theta": "rot_angles",
                "center": "rot_center",
                "is_radians": false,
                "perform_minus_log": true
            },
            "outputs": ["result"]
        },
        {
            "name": "task9",
            "function": "imars3d.backend.io.data.save_data",
            "inputs": {
                "data": "result",
                "filename": "test",
                "outputdir" : "outputdir"
            },
            "outputs": []
        }
    ]
}

=== ornlneutronimaging/iMars3D/tests/data/json/good_non_interactive.json
{
    "facility": "HFIR",
    "instrument": "CG1D",
    "ipts": "IPTS-1234",
    "name": "name for reconstruced ct scans",
    "workingdir": "/path/to/dir",
    "outputdir": "/path/to/dir",
    "tasks": [
        {
            "name": "load",
            "function": "imars3d.backend.io.data.load_data",
            "inputs": {
                "filenames": []
            },
            "outputs": ["ct"]
        },
        {
            "name": "gamma",
            "function": "imars3d.backend.corrections.gamma_filter.GammaFilter",
            "inputs": {
                "ct_series": "ct",
                "workdir": "workingdir"
            },
            "outputs": ["ct"]
        },
        {
            "name": "save",
            "function": "imars3d.backend.io.data.save_data",
            "inputs": {
                "ct_series": "ct",
                "path": "workingdir"
            }
        },
        {
            "name": "determine_tilt_correction",
            "function": "imars3d.backend.diagnostics.tilt.tilt_correction",
            "inputs": {
                "ct_series": "ct"
            },
            "outputs": ["tilt_angle"]
        },
        {
            "name": "tilt_corection",
            "function": "imars3d.backend.diagnostics.tilt.apply_tilt_correction_correction",
            "inputs": {
                "ct_series": "ct",
                "angle": "determine_tilt_correction.tilt_angle"
            },
            "outputs": ["ct"]
        },
        {
            "name": "save",
            "function": "imars3d.backend.io.data.save_data",
            "inputs": {
                "ct_series": "ct",
                "path": "ouputdir"
            }
        }
    ]
}

=== ornlneutronimaging/iMars3D/tests/data/json/partial_non_interactive_full.json
{
    "facility": "HFIR",
    "instrument": "CG1D",
    "ipts": "IPTS-1234",
    "name": "name for reconstructed ct scans",
    "workingdir": "/path/to/working/dir",
    "outputdir": "/tmp/imars3d/",
    "tasks": [{
            "name": "task1",
            "function": "imars3d.backend.dataio.data.load_data",
            "inputs": {
                "ct_dir": "tests/data/imars3d-data/HFIR/CG1D/IPTS-25777/raw/ct_scans/iron_man",
                "ob_dir": "tests/data/imars3d-data/HFIR/CG1D/IPTS-25777/raw/ob/Oct29_2019/",
                "dc_dir": "tests/data/imars3d-data/HFIR/CG1D/IPTS-25777/raw/df/Oct29_2019/",
                "ct_fnmatch": "*.tiff",
                "ob_fnmatch": "*.tiff",
                "dc_fnmatch": "*.tiff"
            },
            "outputs": ["result", "ob", "dc", "rot_angles"]
        },
        {
            "name": "task9",
            "function": "imars3d.backend.dataio.data.save_data",
            "inputs": {
                "data": "result",
                "name": "testfull",
                "outputbase" : "outputdir"
            },
            "outputs": []
        }
    ]
}
